# permissions for end users to view ironicapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ironicapi-viewer-role
rules:
- apiGroups:
  - ironic.openstack.org
  resources:
  - ironicapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ironic.openstack.org
  resources:
  - ironicapis/status
  verbs:
  - get
