# permissions for end users to view ironics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ironic-viewer-role
rules:
- apiGroups:
  - ironic.openstack.org
  resources:
  - ironics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ironic.openstack.org
  resources:
  - ironics/status
  verbs:
  - get
