# permissions for end users to view ironicapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ironicconductor-viewer-role
rules:
- apiGroups:
  - ironic.openstack.org
  resources:
  - ironicconductors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ironic.openstack.org
  resources:
  - ironicconductors/status
  verbs:
  - get
