apiVersion: ironic.openstack.org/v1beta1
kind: Ironic
metadata:
  name: ironic
spec:
  serviceUser: ironic
  secret: osp-secret
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  storageClass: local-storage
  ironicAPI: {}
  ironicConductors:
  - storageRequest: 10G
  ironicInspector: {}
  ironicNeutronAgent: {}
