apiVersion: ironic.openstack.org/v1beta1
kind: Ironic
metadata:
  name: ironic
  namespace: openstack
spec:
  serviceUser: ironic
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  storageClass: standard-csi
  ironicAPI:
    replicas: 1
    containerImage: quay.io/tripleozedcentos9/openstack-ironic-api:current-tripleo
  ironicConductors:
  - replicas: 1
    containerImage: quay.io/tripleozedcentos9/openstack-ironic-conductor:current-tripleo
    pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
    storageRequest: 10G
  - conductorGroup: auckland
    replicas: 1
    containerImage: quay.io/tripleozedcentos9/openstack-ironic-conductor:current-tripleo
    pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
    storageRequest: 10G
    storageClass: standard-csi-auckland
  - conductorGroup: stockholm
    replicas: 1
    containerImage: quay.io/tripleozedcentos9/openstack-ironic-conductor:current-tripleo
    pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
    storageRequest: 10G
    storageClass: standard-csi-stockholm
  ironicInspector:
    replicas: 1
    containerImage: quay.io/tripleozedcentos9/openstack-ironic-inspector:current-tripleo
    pxeContainerImage: quay.io/tripleozedcentos9/openstack-ironic-pxe:current-tripleo
  secret: ironic-secret
