apiVersion: ironic.openstack.org/v1beta1
kind: Ironic
metadata:
  name: ironic
  namespace: openstack
spec:
  serviceUser: ironic
  images:
    api: quay.io/podified-antelope-centos9/openstack-ironic-api:current-podified
    conductor: quay.io/podified-antelope-centos9/openstack-ironic-conductor:current-podified
    inspector: quay.io/podified-antelope-centos9/openstack-ironic-inspector:current-podified
    pxe: quay.io/podified-antelope-centos9/openstack-ironic-pxe:current-podified
    neutronAgent: quay.io/podified-antelope-centos9/openstack-ironic-neutron-agent:current-podified
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  storageClass: local-storage
  ironicAPI:
    replicas: 1
  ironicConductors:
  - replicas: 1
    storageRequest: 10G
  ironicInspector:
    replicas: 1
  ironicNeutronAgent:
    replicas: 1
  secret: osp-secret
