apiVersion: ironic.openstack.org/v1beta1
kind: Ironic
metadata:
  name: ironic
spec:
  standalone: true
  serviceUser: ironic
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  storageClass: local-storage
  ironicAPI:
    replicas: 1
  ironicConductors:
  - replicas: 1
    storageRequest: 10G
  ironicInspector:
    replicas: 1
  secret: ironic-secret
