apiVersion: ironic.openstack.org/v1beta1
kind: Ironic
metadata:
  name: ironic
spec:
  serviceUser: ironic
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  storageClass: local-storage
  ironicAPI:
    replicas: 1
  ironicConductors:
  - replicas: 1
    storageRequest: 10G
  - conductorGroup: auckland
    replicas: 1
    storageRequest: 10G
  - conductorGroup: stockholm
    replicas: 1
    storageRequest: 10G
  ironicInspector:
    replicas: 1
  ironicNeutronAgent:
    replicas: 1
  secret: osp-secret
